### ISSUE TITLE
[ON HOLD] Support sticky sidebar ad units via blocks-based widget editor (WP 5.8)

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-ads#143] opened 2021-07-09 17:59 UTC
WP 5.8 introduces the [block widget editor](https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/). Our experimental feature to enable sticky sidebar ad units in the sidebar widget area no longer works with this editor because the [`widget` method in class-newspack-ads-widget.php](https://github.com/Automattic/newspack-ads/blob/master/includes/class-newspack-ads-widget.php#L35) is no longer fired by blocks-based widgets in WP 5.8, therefore our `stick-to-top` class name is never added to the widget's container. The widget block editor also uses a different UI which doesn't show the "Stick to top" option at all.

The new widget block editor does provide a [filter for the widget container's class names](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-widget-block.php#L169), but the filter doesn't really provide enough info about what's inside the widget to be useful for this. Could use some ideas on how we might bring this feature into the new widget editor.

Ideas:

- Move "stick to top" to the ad unit's block attributes instead of in the widget. We'd still need to figure out a way to read the block's attributes from the widget block editor instance in order to know whether to add the class name.
- Move "stick to top" to the widget area's editor sidebar instead of the widget item or block itself. Since each widget area can only contain one sticky element, this would let us define the sticky behavior on the widget area itself. I'm not sure yet if it's possible to actually add elements to this sidebar, though.

<img width="276" alt="Screen Shot 2021-07-09 at 12 01 36 PM" src="https://user-images.githubusercontent.com/2230142/125118932-a066fc80-e0ad-11eb-8af6-2944cfe5d4dd.png">

**Comment by dkoo** [comment] 2021-07-09 19:24
Note that it is still possible to use the Legacy Widget block to place a legacy Ad Unit widget and use the sticky option, so this provides a good workaround until we can offer proper block-based widget support.

**Comment by adekbadek** [comment] 2021-07-14 10:00
> Our experimental feature to enable sticky sidebar ad units in the sidebar widget area no longer works with this editor because the widget method in class-newspack-ads-widget.php is no longer fired by blocks-based widgets in WP 5.8, therefore our stick-to-top class name is never added to the widget's container. The widget block editor also uses a different UI which doesn't show the "Stick to top" option at all.

The (legacy) widget works, as you point out in the second comment. The issue is with the Ad Unit **block**, which can now be inserted in the widgets area, but does not offer the "stick-to-top" checkbox. Just making sure we're on the same page.

**Comment by adekbadek** [comment] 2021-07-14 10:45
Was too quick to self-assign, but I re-read the original comment:

> The new widget block editor does provide a filter for the widget container's class names, but the filter doesn't really provide enough info about what's inside the widget to be useful for this. 

[`:has()` pseudo-selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) would be a solution, but it's not implemented by any browser yet.

Started work on this on [`fix/sticky-ad-in-block`](https://github.com/Automattic/newspack-ads/tree/fix/sticky-ad-in-block). I think it's best to replicate the widget logic in block, since the widget and the block are essentially different creatures, and the former will become obsolete.

**Comment by dkoo** [comment] 2021-07-14 15:49
> I think it's best to replicate the widget logic in block, since the widget and the block are essentially different creatures, and the former will become obsolete.

That was my thinking, too, and I had begun playing around with replicating the behavior using block attributes, but I didn't get as far as you have. Thanks for getting things going!

**Comment by adekbadek** [comment] 2022-04-13 09:58
> If we ever do decide to roll back the rollback of the block widget editor

Now it happened! https://github.com/Automattic/newspack-plugin/pull/1550

@miguelpeixe – could you have a look at this? With the latest refactoring and block work, seems like you're in best position to tackle this. Is it still a relevant issue?

**Comment by miguelpeixe** [comment] 2022-04-13 13:16
Thanks, @adekbadek!

Another feature that has been introduced since this issue is the "before/after" widget area global placements. One of the global placements feature is the "stick to top" that can have its support enabled on the placement registration.

The sidebar is currently registered with this support:

https://github.com/Automattic/newspack-ads/blob/f7fdc03ccdb55d90d3077d9409d796bc589a362c/includes/class-sidebar-placements.php#L135-L137

If the publisher uses the "after sidebar" placement with "stick to top" toggled on, the sticky behaves as expected in classic widgets or block-based widgets modes.

I believe this should be the official way. Ad unit blocks shouldn't have an option that only works in one particular position.

WDYT, @kmwilkerson ?

**Comment by kmwilkerson** [comment] 2022-04-19 20:30
I agree @miguelpeixe -- having the behavior function the same across both is ideal!

**Comment by miguelpeixe** [comment] 2022-04-19 20:30
Thanks, Katie! Closing the issue then.

**Closed by miguelpeixe** 2022-04-19 20:30 UTC
Labels: enhancement, On Hold
